import { Type, type Static } from "typebox";

/** API 使用的稳定错误码，客户端不得依赖展示文案判断流程。 */
export const ApiErrorCodeSchema = Type.Union([
  Type.Literal("VALIDATION_FAILED"),
  Type.Literal("UNAUTHENTICATED"),
  Type.Literal("FORBIDDEN"),
  Type.Literal("NOT_FOUND"),
  Type.Literal("VERSION_CONFLICT"),
  Type.Literal("SESSION_BUSY"),
  Type.Literal("SESSION_NOT_FOUND"),
  Type.Literal("SESSION_AGENT_CONFLICT"),
  Type.Literal("INSTANCE_ALREADY_RUNNING"),
  Type.Literal("RUNTIME_GENERATION_RETIRED"),
  Type.Literal("CLIENT_TOO_SLOW"),
  Type.Literal("OPERATION_ABORTED"),
  Type.Literal("CONFIG_COMMIT_FAILED"),
  Type.Literal("CONFIG_ROLLBACK_FAILED"),
  Type.Literal("CONFIG_RECOVERY_REQUIRED"),
  Type.Literal("IMPORT_PREVIEW_EXPIRED"),
  Type.Literal("AGENT_WORKSPACE_COMMIT_FAILED"),
  Type.Literal("AGENT_NOT_FOUND"),
  Type.Literal("AGENT_ARCHIVED"),
  Type.Literal("AGENT_HAS_SESSIONS"),
  Type.Literal("AGENT_REMOVAL_IN_PROGRESS"),
  Type.Literal("AGENT_EXECUTION_FAILED"),
  Type.Literal("KNOWLEDGE_COMMIT_FAILED"),
  Type.Literal("KNOWLEDGE_ROLLBACK_FAILED"),
  Type.Literal("KNOWLEDGE_UPLOAD_LIMIT"),
  Type.Literal("AGENT_DELETE_ROLLBACK_FAILED"),
  Type.Literal("CHECKPOINT_WRITE_FAILED"),
  Type.Literal("WORKSPACE_SCAN_LIMIT"),
  Type.Literal("INVALID_MESSAGE"),
  Type.Literal("INVALID_ATTACHMENT"),
  Type.Literal("INVALID_REFERENCE"),
  Type.Literal("INVALID_EVENT_CURSOR"),
  Type.Literal("UNKNOWN_COMMAND"),
  Type.Literal("API_RESPONSE_INVALID"),
  Type.Literal("INTERNAL_ERROR"),
  Type.Literal("REQUEST_FAILED"),
  Type.Literal("AUTH_REQUIRED"),
  Type.Literal("ORIGIN_REJECTED"),
  Type.Literal("NOT_INITIALIZED"),
  Type.Literal("ALREADY_INITIALIZED"),
  Type.Literal("LOGIN_RATE_LIMITED"),
  Type.Literal("INVALID_LOGIN_REQUEST"),
  Type.Literal("INVALID_CREDENTIALS"),
  Type.Literal("INVALID_SETUP"),
  Type.Literal("INVALID_PROFILE"),
  Type.Literal("PROFILE_NOT_FOUND"),
  Type.Literal("AGENT_INVALID"),
  Type.Literal("AGENT_REQUIRED"),
  Type.Literal("INVALID_AGENT_NAME"),
  Type.Literal("INVALID_AGENT_ORDER"),
  Type.Literal("DELETE_OPTIONS_REQUIRED"),
  Type.Literal("REVISION_REQUIRED"),
  Type.Literal("PROMPT_FILES_ONLY"),
  Type.Literal("PROMPT_CONTENT_REQUIRED"),
  Type.Literal("INVALID_PROMPT_FILE"),
  Type.Literal("AVATAR_REQUIRED"),
  Type.Literal("AVATAR_NOT_FOUND"),
  Type.Literal("AVATAR_TOO_LARGE"),
  Type.Literal("INVALID_AVATAR"),
  Type.Literal("INVALID_AVATAR_TYPE"),
  Type.Literal("WORKSPACE_IN_USE"),
  Type.Literal("WORKSPACE_OUTSIDE_DATA"),
  Type.Literal("WORKSPACE_PI_CONFLICT"),
  Type.Literal("WORKSPACE_NOT_ABSOLUTE"),
  Type.Literal("WORKSPACE_ROOT_FORBIDDEN"),
  Type.Literal("WORKSPACE_NOT_DIRECTORY"),
  Type.Literal("WORKSPACE_MIGRATION_FAILED"),
  Type.Literal("DEFAULT_WORKSPACE_FIXED"),
  Type.Literal("INVALID_ARCHIVED_FILTER"),
  Type.Literal("INVALID_SESSION_NAME"),
  Type.Literal("SCHEDULED_TASKS_BOUND"),
  Type.Literal("SCHEDULED_TASK_TARGET_MISSING"),
  Type.Literal("INVALID_MULTIPART"),
  Type.Literal("EMPTY_UPLOAD"),
  Type.Literal("ATTACHMENT_TOO_LARGE"),
  Type.Literal("TOO_MANY_ATTACHMENTS"),
  Type.Literal("INVALID_FILE_PATH"),
  Type.Literal("FILE_NOT_FOUND"),
  Type.Literal("INVALID_PATH"),
  Type.Literal("INVALID_KNOWLEDGE_BASE"),
  Type.Literal("INVALID_KNOWLEDGE_QUERY"),
  Type.Literal("INVALID_KNOWLEDGE_REQUEST"),
  Type.Literal("KNOWLEDGE_BASE_NOT_FOUND"),
  Type.Literal("KNOWLEDGE_DOCUMENT_NOT_FOUND"),
  Type.Literal("KNOWLEDGE_FILE_TOO_LARGE"),
  Type.Literal("UNSUPPORTED_KNOWLEDGE_FILE"),
  Type.Literal("TEXT_PREVIEW_UNAVAILABLE"),
  Type.Literal("CONFLICT"),
  Type.Literal("UNSAFE_LINK"),
  Type.Literal("INVALID_MODEL"),
  Type.Literal("INVALID_MODEL_ORDER"),
  Type.Literal("INVALID_MODEL_REQUEST"),
  Type.Literal("INVALID_MODEL_TEST_REQUEST"),
  Type.Literal("MODEL_NOT_FOUND"),
  Type.Literal("MODEL_IN_USE"),
  Type.Literal("MODEL_SCHEMA_INVALID"),
  Type.Literal("MODEL_TEST_IN_PROGRESS"),
  Type.Literal("MODEL_DISCOVERY_IN_PROGRESS"),
  Type.Literal("MODEL_DISCOVERY_UNAVAILABLE"),
  Type.Literal("MODEL_DISCOVERY_TIMEOUT"),
  Type.Literal("MODEL_DISCOVERY_FAILED"),
  Type.Literal("MODEL_RUNTIME_UNAVAILABLE"),
  Type.Literal("INVALID_PROVIDER_ID"),
  Type.Literal("INVALID_PROVIDER_ORDER"),
  Type.Literal("INVALID_PROVIDER_REQUEST"),
  Type.Literal("INVALID_PROVIDER_BASE_URL"),
  Type.Literal("PROVIDER_ID_EXISTS"),
  Type.Literal("PROVIDER_INVALID"),
  Type.Literal("PROVIDER_IN_USE"),
  Type.Literal("PROVIDER_NOT_FOUND"),
  Type.Literal("PROVIDER_RENAME_CONFIRMATION_REQUIRED"),
  Type.Literal("PROVIDER_RENAME_HISTORY_LIMIT"),
  Type.Literal("UNSUPPORTED_PROVIDER_API"),
  Type.Literal("INVALID_CREDENTIAL"),
  Type.Literal("CREDENTIAL_NOT_FOUND"),
  Type.Literal("INVALID_SETTINGS_REQUEST"),
  Type.Literal("SETTINGS_INVALID"),
  Type.Literal("GLOBAL_ONLY_SETTING"),
  Type.Literal("INVALID_SETTING_TYPE"),
  Type.Literal("SETTING_OUT_OF_RANGE"),
  Type.Literal("UNKNOWN_SETTING"),
  Type.Literal("INVALID_RESOURCE_MODE"),
  Type.Literal("RESOURCE_ID_REQUIRED"),
  Type.Literal("RESOURCE_NOT_FOUND"),
  Type.Literal("PACKAGE_IN_USE"),
  Type.Literal("INSTALL_CONFIRMATION_REQUIRED"),
  Type.Literal("REMOVE_CONFIRMATION_REQUIRED"),
  Type.Literal("INVALID_SCHEDULED_TASK"),
  Type.Literal("SCHEDULED_TASK_NOT_FOUND"),
  Type.Literal("TASK_NOT_FOUND"),
  Type.Literal("HISTORY_NOT_RESTORABLE"),
  Type.Literal("HISTORY_RESTORE_INVALID"),
  Type.Literal("IMPORT_CONFIRMATION_REQUIRED"),
  Type.Literal("IMPORT_INVALID"),
  Type.Literal("RUNTIME_REFRESH_FAILED"),
  Type.Literal("RUNTIME_INITIALIZATION_REFRESH_FAILED"),
  Type.Literal("REFRESH_IN_PROGRESS"),
  Type.Literal("SESSION_AGENT_MISSING"),
]);

export type ApiErrorCode = Static<typeof ApiErrorCodeSchema>;

/** 所有非成功 API 响应共用的文档格式。 */
export const ApiErrorDocumentSchema = Type.Object({
  error: Type.Object({
    code: ApiErrorCodeSchema,
    message: Type.String(),
    requestId: Type.String({ minLength: 1 }),
    details: Type.Optional(Type.Record(Type.String(), Type.Unknown())),
  }, { additionalProperties: false }),
}, { additionalProperties: false });

export type ApiErrorDocument = Static<typeof ApiErrorDocumentSchema>;
